
language: php

php:
  - 7.2
  - 7.3
  - 7.4

install: travis_retry composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

notifications:
  email:
    on_success: never
    on_failure: always
