
language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install: travis_retry composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit --coverage-clover=coverage.clover

notifications:
  email:
    on_success: never
    on_failure: always
